#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
BUILDDIR="$(pwd)/build"
mkdir -p "${BUILDDIR}"
python3 -m venv "${BUILDDIR}/venv"
. "${BUILDDIR}/venv/bin/activate"

pip3 install pyinstaller==5.13.2

# Customize _buildversion.py if build info available in environment
if [ ! -z "${VERSION}" -a ! -z "${BLD_NUM}" ]; then
    VERSIONPATH="${BUILDDIR}/version"
    mkdir -p "${VERSIONPATH}"
    cat <<EOF > "${VERSIONPATH}/_buildversion.py"
__version__ = "${VERSION}"
__build__ = "${BLD_NUM}"
EOF
else
    VERSIONPATH=""
fi

echo Installing patch_via_gerrit requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

echo Compiling patch_via_gerrit
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}
pyinstaller --log-level DEBUG \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile \
    --paths "${VERSIONPATH}:${SCRIPTPATH}" \
    --name patch_via_gerrit \
    ${SCRIPTPATH}/patch_via_gerrit/scripts/main.py
